name = "instasaqlovchi"
main = "src/index.js"
compatibility_date = "2026-03-17"
workers_dev = true

[vars]
TELEGRAM_WEBHOOK_PATH = "/webhook"
RAPIDAPI_ENDPOINT = "https://youtube-to-mp4.p.rapidapi.com/url-title"
RAPIDAPI_HOST = "youtube-to-mp4.p.rapidapi.com"
RAPIDAPI_TITLE = "Telegram MP4 Download"
